"""initial schema

Revision ID: 3dac2b7d80bb
Revises: 
Create Date: 2026-04-11 18:41:37.713514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dac2b7d80bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Text(), server_default='raw', nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keywords_scraped_at', 'keywords', ['scraped_at'], unique=False)
    op.create_index('idx_keywords_status', 'keywords', ['status'], unique=False)
    op.create_index('idx_keywords_status_updated', 'keywords', ['status', 'updated_at'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('keywords_inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_runs_started_at', 'scrape_runs', ['started_at'], unique=False)
    op.create_index('idx_scrape_runs_status', 'scrape_runs', ['status'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('source_site', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('idx_articles_keyword_id', 'articles', ['keyword_id'], unique=False)
    op.create_table('keyword_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('expanded_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_article_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id')
    )
    op.create_table('keyword_justifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword_id')
    )
    op.create_index('idx_justifications_is_relevant', 'keyword_justifications', ['is_relevant'], unique=False)
    
    # Custom trigger for updated_at
    op.execute("""
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$ language 'plpgsql';
    """)
    op.execute("""
    CREATE TRIGGER update_keywords_updated_at
    BEFORE UPDATE ON keywords
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_justifications_is_relevant', table_name='keyword_justifications')
    op.drop_table('keyword_justifications')
    op.drop_table('keyword_enrichments')
    op.drop_index('idx_articles_keyword_id', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_scrape_runs_status', table_name='scrape_runs')
    op.drop_index('idx_scrape_runs_started_at', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('idx_keywords_status_updated', table_name='keywords')
    op.drop_index('idx_keywords_status', table_name='keywords')
    op.drop_index('idx_keywords_scraped_at', table_name='keywords')
    op.drop_table('keywords')
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;")
    # ### end Alembic commands ###
